version: '2'

services:

  redis:
    image: redis:5.0.5
    ports:
      - 6379:6379

  airflow:
    build:
      context: .
      dockerfile: ./docker/airflow/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=currency
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./airflow/:/code
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=currency
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./airflow/:/code
    depends_on:
      - redis

  beat:
    build:
      context: .
      dockerfile: ./docker/beat/Dockerfile
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=currency
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./airflow/:/code
    depends_on:
      - redis

  db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=currency
    ports:
      - 5432:5432
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  